### ISSUE TITLE
Initial setup issues

### ISSUE THREAD

**Issue by careless25** [paschmann/rasa-ui#31]
Hey! 
This seems like an awesome project but it's really lacking documentation or I can't find it. 

Anyways the issue I am facing: 
1. Installed rasa_nlu, node, postgres (ran the db_Create.sql script). 
2. Installed the rasa_ui on the same server and changed the package.json to localhost:port for both postgres and rasa

Now when I login via the ui (admin/admin) and try to create an agent. It does nothing. I don't see anything in the npm logs. 

Any ideas?

**Comment by careless25** [comment]
Actually in the web console: 

```
Possibly unhandled rejection: {"data":{"status":"error","message":"Invalid status code: 0"},"status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","data":{"agent_name":"Test"},"url":"/api/v2/agents","headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6IlBvcnRhbCBBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNTE2MzgzMTk0fQ.4Us_Efi9SYOqLcEw5y3ENQfdrTRsI8EXVLnKxVvAcbI","Content-Type":"application/json;charset=utf-8"}},"statusText":"unknown"}
```

**Comment by pradeepmvn** [comment]
@careless25 Can you check the database access , such as username and password.  Error code 500 tell me that some internal server while writing data.

Yes agreed that documentation could be better. I will be looking at updating some of it. We could definitely get some contribution if you are interested :)

**Comment by careless25** [comment]
Yes, I got past the database. Had to create user/update password and change the postgres config files. Leave this issue open and I can write up the documentation for what I did here.

**Comment by paschmann** [comment]
@careless25 - please check the [wiki](https://github.com/paschmann/rasa-ui/wiki) - we do have some docu but could use an update I am sure.

**Comment by careless25** [comment]
@paschmann I did read the wiki. Followed it to a T but ran into issues. Like i said I will update the docs/wiki when I get some time.

**Comment by paschmann** [comment]
Thanks for the feedback @careless25 - I just did a clean install and found a few issues, I added a couple details to the wiki as well.

**Comment by pradeepmvn** [comment]
@careless25 thanks for update 
@paschmann  I think readme and wiki need to be cleaned and updated. I was planning to add some FAQ's link into wiki. Any other suggestions ?

**Comment by careless25** [comment]
Created agent succesfully but then: 

```
DB Error while getting agent details.
TypeError: Cannot read property 'agent_id' of undefined
    at /home/ubuntu/rasaui/server/routes/middleware.js:215:48
    at NodeCache.module.exports.NodeCache.get (/home/ubuntu/rasaui/node_modules/node-cache/lib/node_cache.js:101:11)
    at NodeCache.get (/home/ubuntu/rasaui/node_modules/node-cache/lib/node_cache.js:12:59)
    at /home/ubuntu/rasaui/server/routes/middleware.js:208:23
    at tryCatcher (/home/ubuntu/rasaui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/rasaui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/rasaui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/rasaui/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/rasaui/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ubuntu/rasaui/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ubuntu/rasaui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ubuntu/rasaui/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
rasa_response:+++ {
  "error": "No project found with name 'Default'."
}
TypeError: Cannot read property 'name' of undefined
    at /home/ubuntu/rasaui/server/routes/middleware.js:165:59
    at NodeCache.module.exports.NodeCache.get (/home/ubuntu/rasaui/node_modules/node-cache/lib/node_cache.js:101:11)
    at NodeCache.get (/home/ubuntu/rasaui/node_modules/node-cache/lib/node_cache.js:12:59)
    at updateCacheWithRasaNluResponse (/home/ubuntu/rasaui/server/routes/middleware.js:158:17)
    at Request._callback (/home/ubuntu/rasaui/server/routes/middleware.js:105:7)
    at Request.self.callback (/home/ubuntu/rasaui/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/ubuntu/rasaui/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/rasaui/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
```

**Comment by paschmann** [comment]
@careless25 - I am looking into this - as I am getting the same error.

**Comment by paschmann** [comment]
@careless25 - seems like a bug with synonyms. I have committed a small fix, you want to merge it locally and retry. For reference, you need to run your training before you can test using the sidebar.

**Comment by careless25** [comment]
@paschmann Still facing the issue. I am running the default rasa model. No training, no data. Just tried to parse "Hi" and it gives the same error.

**Comment by pradeepmvn** [comment]
> No training, no data

@careless25 Did you not create an Agent with an intent and train it? To be able to parse a request, Rasa NLU need to have a model created. You should see it in the Training page.

> But does this UI allow for creating a completely new Rasa model from scratch?

Yes it does. That is the main intention of rasa-ui. So once a model is created, you should select it from the drop down on the side test panel and execute a parse request.

**Comment by careless25** [comment]
Ok so I created an agent, then created a single intent and added a couple examples.
Then going into the training tab -> selected agent and started training:

npm logs: 
```
Error occured while training. Response Code : 500 Body{
  "error": "2"
}
```

**Comment by pradeepmvn** [comment]
@careless25 This error comes from python rasa_nlu server. Please check if the server is up and running and see if the status is ok.

**Comment by careless25** [comment]
This is what I see in the rasa server logs: 

```
2018-01-19 21:50:04+0000 [-] "127.0.0.1" - - [19/Jan/2018:21:50:03 +0000] "GET /status HTTP/1.1" 200 243 "-" "-"
INFO:rasa_nlu.utils.spacy_utils:Trying to load spacy model with name 'en'
2018-01-19 21:50:05+0000 [-] "127.0.0.1" - - [19/Jan/2018:21:50:04 +0000] "GET /config HTTP/1.1" 200 1533 "-" "-"
INFO:rasa_nlu.components:Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
2018-01-19 21:50:08+0000 [-] "127.0.0.1" - - [19/Jan/2018:21:50:07 +0000] "POST /train?project=Default HTTP/1.1" 500 18 "-" "-"
2018-01-19 21:50:09+0000 [-] "127.0.0.1" - - [19/Jan/2018:21:50:08 +0000] "GET /status HTTP/1.1" 200 243 "-" "-"
2018-01-19 21:50:10+0000 [-] "127.0.0.1" - - [19/Jan/2018:21:50:09 +0000] "GET /config HTTP/1.1" 200 1533 "-" "-"
2018-01-19 21:50:14+0000 [-] "127.0.0.1" - - [19/Jan/2018:21:50:13 +0000] "GET /status HTTP/1.1" 200 243 "-" "-"
```

**Comment by careless25** [comment]
Why is there a limit on the uploading of existing data?

I am running into this error for our existing data: 
```
{message: "request entity too large", expected: 154631, length: 154631, limit: 102400, type: "entity.too.large"}
```

**Comment by careless25** [comment]
Actually the training issue might be something with Rasa-ui. As soon as I click "Start Training", the UI changes from the dataset to "No object" and then clicking "Download File" also downloads a blank file.

**Comment by careless25** [comment]
I am not sure how to update the wiki but here is how I would phrase it: 


**PostgreSQL Install**

Open terminal and run the following commands:

[PostgreSQL](https://www.postgresql.org/) - Used for storing training data (entities, intents, synonyms, etc.)

```bash
sudo apt-get update
sudo apt-get install postgresql postgresql-contrib
sudo -i -u postgres
```

Download the Schema and create the objects

```bash
wget https://raw.githubusercontent.com/paschmann/rasa-ui/master/resources/dbcreate.sql
psql
create database rasaui;
ALTER USER postgres PASSWORD 'xxxxxxxxxx';
\c rasaui
\i dbcreate.sql
\q
logout
```

**NodeJs Install**

[Node.js/npm](https://nodejs.org/en/) - Serves Rasa UI and acts as a middleware server for logging (to the PostgreSQL DB)

```bash
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y build-essential
sudo apt-get install -y nodejs
```

**Comment by pradeepmvn** [comment]
@careless25 Thanks for the feedback. This helps to document in the wiki.
Regarding the training page, once you click training the object becomes empty and the training starts. This is current functionality. Can you open another issue for upload data size and close this?
